# Generated by Django 4.0.4 on 2022-04-24 13:22

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_user_last_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Cтатус получения заказов'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
